
# HTTP服务启动端口
server:
  port: 40000

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
#    username: root
#    password: 1003
#    driver-class-name: com.mysql.cj.jdbc.Driver

file-sync:
  server:
    path: C:\Users\26044\IdeaProjects\file-sync\sync-dir\server

# netty 配置
netty:
  # boss线程数量
  boss: 1
  # worker线程数量
  worker: 3
  # 连接超时时间
  timeout: 6000
  # 服务器主端口
  port: 40001
