
# HTTP服务启动端口
server:
  port: 44400

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
#    username: root
#    password: 1003
#    driver-class-name: com.mysql.cj.jdbc.Driver

file-sync:
  server:
    path: C:\Users\26044\IdeaProjects\file-sync\sync-dir\server

# netty 配置
netty:
  # boss线程数量
  boss: 1
  # worker线程数量
  worker: 3
  # 连接超时时间
  timeout: 6000
  # 服务器主端口
  port: 44401

spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/file_sync_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1003

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1

logging:
  level:
    root: debug