
# HTTP服务启动端口
server:
  port: 22200

file-sync:
  client:
    path: C:\Users\26044\IdeaProjects\file-sync\sync-dir\client-1
    interval: 3
    deviceId: 1
  server:
    host: 127.0.0.1
    port: 44400

spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

netty:
  client:
    worker: 4
  server:
    host: 127.0.0.1
    port: 44401
